<div class="row">   
    <div class="col-xs-4">
        <h2>
        <p class="text-primary">Organizacion</p>
        </h2>
    </div>
    <div class="col-xs-8">
        El equipo encargado del evento esta constituida por docentes y estudiantes 
        de la carrera de Ingenieria Informatica de la Facultad de Ciencias 
        Integradas del Gran Chaco constituidos en comisiones, con las cuales
        se pretende garantizar el exito de este evento muy importante en la
        actualizacion continua de las Tic's. 
        
        
    </div>        

</div>
