<div class="row">
    <div class="col-lg-6">
        <div>
            <ul>
                <li>turismo</li>
                <li>restaurants</li>
                <li>videojuegos</li>
            </ul>
        </div>
    </div>
    <div class="col-lg-6">
        <ul>
            <li>Mapa</li>
            <li>Hoteles</li>
            <li>Encargados</li>

        </ul>

    </div>

 <iframe width="640" height="480" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.bo/maps?f=q&amp;source=s_q&amp;hl=es-419&amp;geocode=&amp;q=Auditorio+Evo+Morales&amp;aq=&amp;sll=-22.021671,-63.681283&amp;sspn=0.001514,0.002642&amp;ie=UTF8&amp;t=h&amp;ll=-22.021589,-63.681473&amp;spn=0.001194,0.001717&amp;z=19&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com.bo/maps?f=q&amp;source=embed&amp;hl=es-419&amp;geocode=&amp;q=Auditorio+Evo+Morales&amp;aq=&amp;sll=-22.021671,-63.681283&amp;sspn=0.001514,0.002642&amp;ie=UTF8&amp;t=h&amp;ll=-22.021589,-63.681473&amp;spn=0.001194,0.001717&amp;z=19" style="color:#0000FF;text-align:left">Ver mapa más grande</a></small>
</div>
