    <div class="container">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Disertante1') ?></h3>
                
            </div>
            
            <div class="panel-body centrarimg">
                
                <div class="row">
                    <div class="col-md-4">
                   <a href="#" daclass="thumbnail">
                  <img data-src="holder.js/200x150/#86D3FF:#0F3CFF" alt="...">
                  </a>
                    
                <!--<img src="<?php echo $this->basePath('img/F_Beltran.jpg') ?>" alt="..." class="img-thumbnail" >
                -->
                    </div>
                    <div class="col-md-8">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi, quaerat, et quae ex porro odit totam cupiditate eius voluptatum possimus? Tempora, possimus, libero eaque atque velit voluptas ex nulla culpa.
                    </div>
                    </div>
                    </div>
               
            </div>
        </div>
         <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Disertante2') ?></h3>
                
            </div>
            
            <div class="panel-body centrarimg">
                
                <div class="row">
                    <div class="col-md-4">
                 <a href="#" daclass="thumbnail">
                  <img data-src="holder.js/200x150/#86D3FF:#0F3CFF" alt="...">
                  </a>                
                <!--<img src="<?php echo $this->basePath('img/F_Castro.jpg') ?>" alt="..." class="img-thumbnail" >
                -->    
                </div>
                    <div class="col-md-8">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque, voluptatibus officiis quo perferendis repellendus voluptate dolore pariatur doloribus accusantium delectus distinctio deserunt saepe laudantium quibusdam aliquid corrupti placeat tenetur quidem.
                    </div>
                    </div>
                    </div>
               
            </div>
        </div>
         <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Disertante2') ?></h3>
                
            </div>
            
            <div class="panel-body centrarimg">
                
                <div class="row">
                    <div class="col-md-4">
                    <a href="#" daclass="thumbnail">
                  <img data-src="holder.js/200x150/#86D3FF:#0F3CFF" alt="...">
                  </a>
              <!--  <img src="<?php echo $this->basePath('img/F_Choque.jpg') ?>" alt="..." class="img-thumbnail" >
              -->    
              </div>
                    <div class="col-md-8">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa, expedita cupiditate commodi eius dolore ea dolor natus fugit magnam nemo est magni fugiat beatae voluptatem dicta ratione cumque molestiae recusandae!
                    </div>
                    </div>
                    </div>
               
            </div>
        </div>
         <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Disertante3') ?></h3>
                
            </div>
            
            <div class="panel-body centrarimg">
                
                <div class="row">
                    <div class="col-md-4">
                    <a href="#" daclass="thumbnail">
                  <img data-src="holder.js/200x150/#86D3FF:#0F3CFF" alt="...">
                  </a>
                <!--<img src="<?php echo $this->basePath('img/F_Prudencio.jpg') ?>" alt="..." class="img-thumbnail" >
                -->    
                </div>
                    <div class="col-md-8">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam, sit, ab, dolore sint repudiandae magni et rem repellat consequuntur autem fuga obcaecati rerum nisi deleniti quis quam inventore voluptate ipsam.
                    </div>
                    </div>
                    </div>
               
            </div>
        </div>
    </div>