<div class="row">
   
    <div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Marcelo Antonio Castro') ?></h3>
                
            </div>
            
            <div class="panel-body centrarimg">
                
                <div class="row">
                    <div class="col-md-4">
                    
                <img src="<?php echo $this->basePath('img/F_Beltran.jpg') ?>" alt="..." class="img-thumbnail" >
                    </div>
                    <div class="col-md-8">
Ingeniero en Sistemas de Información de la Universidad Tecnológica Nacional, Facultad de Córdoba - Argentina. Doctorando en Ciencias Informáticas. Magíster en Ingeniería de Software. Especialista en Gestión Pública. Diplomado Internacional en Gobierno Electrónico y Gestión Pública. 
Profesor Adjunto Ordinario Dedicación Exclusiva de las Carreras de Ingeniería Informática y Licenciatura en Sistemas, Facultad de Ingeniería, U.N.Ju.
Coordinador de todas las Carreras de grado, que se dictan en la Facultad de Ingeniería y Director de Carrera Ingeniería Informática que se dicta en la Facultad de Ingeniería, dependiente de la Universidad Nacional de Jujuy.
                    </div>
                    </div>
                    </div>
               
            </div>
        </div>
         <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Hardy Beltrán Monasterios') ?></h3>
                
            </div>
            
            <div class="panel-body centrarimg">
                
                <div class="row">
                    <div class="col-md-4">
                    
                <img src="<?php echo $this->basePath('img/F_Castro.jpg') ?>" alt="..." class="img-thumbnail" >
                    </div>
                    <div class="col-md-8">
Ingeniero en Sistemas de Información de la Universidad Tecnológica Nacional, Facultad de Córdoba - Argentina. Doctorando en Ciencias Informáticas. Magíster en Ingeniería de Software. Especialista en Gestión Pública. Diplomado Internacional en Gobierno Electrónico y Gestión Pública. 
Profesor Adjunto Ordinario Dedicación Exclusiva de las Carreras de Ingeniería Informática y Licenciatura en Sistemas, Facultad de Ingeniería, U.N.Ju.
Coordinador de todas las Carreras de grado, que se dictan en la Facultad de Ingeniería y Director de Carrera Ingeniería Informática que se dicta en la Facultad de Ingeniería, dependiente de la Universidad Nacional de Jujuy.
                    </div>
                    </div>
                    </div>
               
            </div>
        </div>
         <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Guillermo Choque Aspiazu') ?></h3>
                
            </div>
            
            <div class="panel-body centrarimg">
                
                <div class="row">
                    <div class="col-md-4">
                    
                <img src="<?php echo $this->basePath('img/F_Choque.jpg') ?>" alt="..." class="img-thumbnail" >
                    </div>
                    <div class="col-md-8">
Ingeniero en Sistemas de Información de la Universidad Tecnológica Nacional, Facultad de Córdoba - Argentina. Doctorando en Ciencias Informáticas. Magíster en Ingeniería de Software. Especialista en Gestión Pública. Diplomado Internacional en Gobierno Electrónico y Gestión Pública. 
Profesor Adjunto Ordinario Dedicación Exclusiva de las Carreras de Ingeniería Informática y Licenciatura en Sistemas, Facultad de Ingeniería, U.N.Ju.
Coordinador de todas las Carreras de grado, que se dictan en la Facultad de Ingeniería y Director de Carrera Ingeniería Informática que se dicta en la Facultad de Ingeniería, dependiente de la Universidad Nacional de Jujuy.
                    </div>
                    </div>
                    </div>
               
            </div>
        </div>
         <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Arturo Prudencio Nina') ?></h3>
                
            </div>
            
            <div class="panel-body centrarimg">
                
                <div class="row">
                    <div class="col-md-4">
                    
                <img src="<?php echo $this->basePath('img/F_Prudencio.jpg') ?>" alt="..." class="img-thumbnail" >
                    </div>
                    <div class="col-md-8">
Ingeniero en Sistemas de Información de la Universidad Tecnológica Nacional, Facultad de Córdoba - Argentina. Doctorando en Ciencias Informáticas. Magíster en Ingeniería de Software. Especialista en Gestión Pública. Diplomado Internacional en Gobierno Electrónico y Gestión Pública. 
Profesor Adjunto Ordinario Dedicación Exclusiva de las Carreras de Ingeniería Informática y Licenciatura en Sistemas, Facultad de Ingeniería, U.N.Ju.
Coordinador de todas las Carreras de grado, que se dictan en la Facultad de Ingeniería y Director de Carrera Ingeniería Informática que se dicta en la Facultad de Ingeniería, dependiente de la Universidad Nacional de Jujuy.
                    </div>
                    </div>
                    </div>
               
            </div>
        </div>
    </div>
</div>
