<div class="row contenedor">
    <h1> <strong><p class="text-primary">Calendario Oficial</p> </strong></h1>
    <h4> <strong><p class="text-danger">Fecha inicio: jueves 15 de mayo</p> </strong></h4>
    <h4> <strong><p class="text-success">Fecha fin: sabado 17 de mayo</p> </strong></h4>

    <br>
   <div class="table-responsive">
       
  <table class="table table-bordered">
    
<tr class="success">

    <td><h2>Horario </h2>  </td>
    <td><h2>Jueves </h2></td>
    <td> <h2>Viernes </h2></td>
    <td> <h2>Sábado </h2></td>
</tr>

<tr>

    <td><h4>9:00 am </h4>  </td>
    <td class="warning"><h4>Inaguracion </h4></td>
    <td class="info"> <h4>Tutorial</h4></td>
    <td class="active"> <h4>Tutorial</h4></td>
       
</tr>

<tr>

    <td><h4>10:00 am </h4>  </td>
    <td class="warning"><h4>Tutorial </h4></td>
    <td class="info"> <h4>Tutorial</h4></td>
    <td class="active"> <h4>Tutorial</h4></td>
       
</tr>
<tr>

    <td><h4>11:00 am </h4>  </td>
    <td class="warning"><h4>Conferencia</h4></td>
    <td class="info"> <h4>Conferencia</h4></td>
    <td class="active"> <h4>Conferencia</h4></td>
       
</tr>

<tr>

    <td class='danger'><h4>12:00 am </h4>  </td>
    <td class="danger"><h4>descanso </h4></td>
    <td class="danger"> <h4>descanso</h4></td>
    <td class="danger"> <h4>descanso</h4></td>
       
</tr>

<tr>

    <td><h4>14:00 </h4>  </td>
    <td class="warning"><h4>Tutorial </h4></td>
    <td class="info"> <h4>Tutorial</h4></td>
    <td class="active"> <h4>Tutorial</h4></td>
       
</tr>

<tr>

    <td><h4>15:00 </h4>  </td>
    <td class="warning"><h4>Tutorial</h4></td>
    <td class="info"> <h4>Tutorial</h4></td>
    <td class="active"> <h4>Tutorial</h4></td>
       
</tr>
<tr>

    <td><h4>16:00 </h4>  </td>
    <td class="warning"><h4>Conferencia</h4></td>
    <td class="info"> <h4>Conferencia</h4></td>
    <td class="active"> <h4>Conferencia</h4></td>
       
</tr>

<tr>

    <td class='danger'><h4>18:00 </h4>  </td>
    <td class="danger"><h4>descanso </h4></td>
    <td class="danger"> <h4>descanso</h4></td>
    <td class="danger"> <h4>descanso</h4></td>
       
</tr>

<tr>

    <td><h4>19:00 </h4>  </td>
    <td class="warning"><h4>Tutorial</h4></td>
    <td class="info"> <h4>Tutorial</h4></td>
    <td class="active"> <h4>Tutorial</h4></td>
       
</tr>

<tr>

    <td><h4>20:00 </h4>  </td>
    <td class="warning"><h4>Conferencia</h4></td>
    <td class="info"> <h4>Conferencia</h4></td>
    <td class="active"> <h4>Conferencia</h4></td>
       
</tr>
<tr>

    <td><h4>21:00 </h4>  </td>
    <td class="warning"><h4>Tutorial</h4></td>
    <td class="info"> <h4>Tuitorial</h4></td>
    <td class="active"> <h4>Tutorial</h4></td>
       
</tr>

<tr>

    <td class='danger'><h4>22:00 </h4>  </td>
    <td class="danger"><h4>descanso </h4></td>
    <td class="danger"> <h4>descanso</h4></td>
    <td class="danger"> <h4>descanso</h4></td>
       
</tr>



  </table>
</div>
  </div>
