<div class="row">
    <div class="col-lg-12"><h1>Calendario Oficial</h1></div>
    <br>
  <br>
   <div class="table-responsive">
       
  <table class="table">
    
    <tr>
  <td class="active">horario</td>
  <td class="success">lunes</td>
  <td class="warning">martes</td>
  <td class="danger">miercoles</td>

   
</tr>

<tr class="success">

    <td><h2>horario </h2>  </td>
    <td><h2>lunes </h2></td>
    <td> <h2>martes </h2></td>
    <td> <h2>miercoles </h2></td>
</tr>

<tr>

    <td><h4>9:00 am </h4>  </td>
    <td class="warning"><h4>Inaguracion </h4></td>
    <td class="active"> <h4>Ponencia</h4></td>
    <td class="active"> <h4> taller</h4></td>
       
</tr>

<tr>

    <td><h4>10:00 am </h4>  </td>
    <td class="warning"><h4>Inaguracion </h4></td>
    <td class="active"> <h4>Ponencia</h4></td>
    <td class="active"> <h4> taller</h4></td>
       
</tr>
<tr>

    <td><h4>11:00 am </h4>  </td>
    <td class="warning"><h4>Inaguracion </h4></td>
    <td class="active"> <h4>Ponencia</h4></td>
    <td class="active"> <h4> taller</h4></td>
       
</tr>

<tr>

    <td class='danger'><h4>12:00 am </h4>  </td>
    <td class="danger"><h4>descanso </h4></td>
    <td class="danger"> <h4>descanso</h4></td>
    <td class="danger"> <h4>descanso</h4></td>
       
</tr>

<tr>

    <td><h4>9:00 am </h4>  </td>
    <td class="warning"><h4>Inaguracion </h4></td>
    <td class="active"> <h4>Ponencia</h4></td>
    <td class="active"> <h4> taller</h4></td>
       
</tr>

<tr>

    <td><h4>10:00 am </h4>  </td>
    <td class="warning"><h4>Inaguracion </h4></td>
    <td class="active"> <h4>Ponencia</h4></td>
    <td class="active"> <h4> taller</h4></td>
       
</tr>
<tr>

    <td><h4>11:00 am </h4>  </td>
    <td class="warning"><h4>Inaguracion </h4></td>
    <td class="active"> <h4>Ponencia</h4></td>
    <td class="active"> <h4> taller</h4></td>
       
</tr>

<tr>

    <td class='danger'><h4>12:00 am </h4>  </td>
    <td class="danger"><h4>descanso </h4></td>
    <td class="danger"> <h4>descanso</h4></td>
    <td class="danger"> <h4>descanso</h4></td>
       
</tr>

<tr>

    <td><h4>9:00 am </h4>  </td>
    <td class="warning"><h4>Inaguracion </h4></td>
    <td class="active"> <h4>Ponencia</h4></td>
    <td class="active"> <h4> taller</h4></td>
       
</tr>

<tr>

    <td><h4>10:00 am </h4>  </td>
    <td class="warning"><h4>Inaguracion </h4></td>
    <td class="active"> <h4>Ponencia</h4></td>
    <td class="active"> <h4> taller</h4></td>
       
</tr>
<tr>

    <td><h4>11:00 am </h4>  </td>
    <td class="warning"><h4>Inaguracion </h4></td>
    <td class="active"> <h4>Ponencia</h4></td>
    <td class="active"> <h4> taller</h4></td>
       
</tr>

<tr>

    <td class='danger'><h4>12:00 am </h4>  </td>
    <td class="danger"><h4>descanso </h4></td>
    <td class="danger"> <h4>descanso</h4></td>
    <td class="danger"> <h4>descanso</h4></td>
       
</tr>



  </table>
</div>
