<div class="row">   
    <div class="col-xs-4">
        <h2>
        <p class="text-primary">Lugar del Evento</p>
        </h2>
    </div>
    <div class="col-xs-8">
        Somos de la carrera de ingenieria informatica de la facultad de ciencias
         <iframe width="640" height="480" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.bo/maps?f=q&amp;source=s_q&amp;hl=es-419&amp;geocode=&amp;q=Auditorio+Evo+Morales&amp;aq=&amp;sll=-22.021671,-63.681283&amp;sspn=0.001514,0.002642&amp;ie=UTF8&amp;t=h&amp;ll=-22.021589,-63.681473&amp;spn=0.001194,0.001717&amp;z=19&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com.bo/maps?f=q&amp;source=embed&amp;hl=es-419&amp;geocode=&amp;q=Auditorio+Evo+Morales&amp;aq=&amp;sll=-22.021671,-63.681283&amp;sspn=0.001514,0.002642&amp;ie=UTF8&amp;t=h&amp;ll=-22.021589,-63.681473&amp;spn=0.001194,0.001717&amp;z=19" style="color:#0000FF;text-align:left">Ver mapa más grande</a></small>

    </div>        

</div>
