<div class="row">   
    <div class="col-xs-4">
        <h2>
        <p class="text-primary">Mision y Vision</p>
        </h2>
    </div>
    <div class="col-xs-8">
        <div class="row">
            Mision:<br>
            Somos de la carrera de ingenieria informatica de la facultad de ciencias
        integradas del Gran Chaco pertenecientes a la Universidad Autonoma Juan Misael Saracho -UAJMS
        </div>
        <div class="row">
            Vision:<br>
            Somos de la carrera de ingenieria informatica de la facultad de ciencias
        integradas del Gran Chaco pertenecientes a la Universidad Autonoma Juan Misael Saracho -UAJMS
        </div>
        
    </div>        

</div>
