<h1>
    <hr>
     <?php echo $this->titulo; ?>
   
</h1>
<hr />
<div class="contenedorform">
<div class="panel panel-default">
  <div class="panel-heading">Formulario de Registro</div>
  <div class="panel-body">
<!--<div class="contenedorform">-->
    <?php
    $form = $this->form;
    $form->prepare();
    
    $form->setAttribute('action',
                    $this->url('preinscripciones',
                               array('controller'=>'preinscripciones', 'action' => 'index'))); 
     $form->prepare();
    
//     $form->setAttributes(array(
//        'action'=>$this->url.'/application/preinscripciones/index',
//        'method'=>'post'
//    ));
    // Get the form label plugin
    $formLabel = $this->plugin('formLabel');

    // Render the opening tag
    echo $this->form()->openTag($form);
    ?>
    <div class="form_element">
     <?php $name = $form->get('cedula');?>
        <div class="row">
        <div class="col-xs-3">
        <?php echo $formLabel->openTag().$name->getOption('label'); ?>
        </div>
        <div class="col-xs-6">
        <?php echo $this->formElementErrors($name);
        echo $formLabel->closeTag();
         echo $this->formInput($name);
        ?>
        </div>
    </div>
    </div>
    
    <div class="form_element">
    <?php $name = $form->get('nombre');?>
        <div class="row">
        <div class="col-xs-3">
        <?php echo $formLabel->openTag().$name->getOption('label'); ?>
        </div>
        <div class="col-xs-9">
        <?php echo $this->formElementErrors($name);
        echo $formLabel->closeTag();
         echo $this->formInput($name);
        ?>
        </div>
    </div>
    </div>
    
     <div class="form_element">
    <?php $name = $form->get('apellido');?>
        <div class="row">
        <div class="col-xs-3">
        <?php echo $formLabel->openTag().$name->getOption('label'); ?>
        </div>
        <div class="col-xs-9">
        <?php echo $this->formElementErrors($name);
        echo $formLabel->closeTag();
         echo $this->formInput($name);
        ?>
        </div>
    </div>
    </div>


    <div class="form_element">
    <?php $name = $form->get('lugar');?>
        <div class="row">
        <div class="col-xs-3">
        <?php echo $formLabel->openTag().$name->getOption('label'); ?>
        </div>
        <div class="col-xs-9">
        <?php echo $this->formElementErrors($name);
        echo $formLabel->closeTag();
         echo $this->formInput($name);
        ?>
        </div>
    </div>
    </div>
    
     <div class="form_element">
    <?php $name = $form->get('telefono');?>
        <div class="row">
        <div class="col-xs-3">
        <?php echo $formLabel->openTag().$name->getOption('label'); ?>
        </div>
        <div class="col-xs-9">
        <?php echo $this->formElementErrors($name);
        echo $formLabel->closeTag();
         echo $this->formInput($name);
        ?>
        </div>
    </div>
    </div>
   
     
     <div class="form_element">
    <?php $name = $form->get('email');?>
        <div class="row">
        <div class="col-xs-3">
        <?php echo $formLabel->openTag().$name->getOption('label'); ?>
        </div>
        <div class="col-xs-9">
        <?php echo $this->formElementErrors($name);
        echo $formLabel->closeTag();
         echo $this->formInput($name);
        ?>
        </div>
    </div>
    </div>
    
     <div class="form_element">
    <?php $name = $form->get('estado');?>
        <div class="row">
        <div class="col-xs-5">
        <?php echo $formLabel->openTag().$name->getOption('label'); ?>
        </div>
        <div class="col-xs-7">
        <?php echo $this->formElementErrors($name);
        echo $formLabel->closeTag();     
        echo $this->formRadio($name);
        ?>
        </div>
    </div>
    </div>
     
     <div class="form_element">
    <?php $name = $form->get('paquete');?>
        <div class="row">
        <div class="col-xs-5">
        <?php echo $formLabel->openTag().$name->getOption('label'); ?>
        </div>
        <div class="col-xs-7">
        <?php echo $this->formElementErrors($name);
        echo $formLabel->closeTag();
         echo $this->formSelect($name);
        ?>
        </div>
    </div>

    </div>
    <div class="form_element">
    <?php $name = $form->get('captcha');?>
        <div class="row">
        <div class="col-xs-5">
        <?php echo $formLabel->openTag().$name->getOption('label'); ?>
        </div>
        <div class="col-xs-7">
        <?php echo $this->formElementErrors($name);
        echo $formLabel->closeTag();
         echo $this->formCaptcha($name);
        ?>
        </div>
    </div>
    </div>
<p class="text-right">
    <?php echo $this->formElement($form->get('send')) ?>
</p>
    <?php echo $this->form()->closeTag() ?>
</div>
  </div>
</div>