<div class="row contenedor">   
    <h1> <strong><p class="text-primary">Inversión</p> </strong></h1>
        
        <br>        
   <div class="table-responsive">
       
  <table class="table table-bordered">
    
    <tr class="success">

    <td><h2>Paquete </h2>  </td>
    <td><h2>Descripcion </h2></td>
    <td> <h2>Precio Estudiantes </h2></td>
    <td> <h2>Precio Profesionales </h2></td>
    </tr>

<tr>

    <td><h4>paq1 </h4>  </td>
    <td class="warning"><h4>1 Tutorial y 1 conferencia </h4></td>
    <td class="info"> <h4>bs. </h4></td>
    <td class="active"> <h4>bs. </h4></td>
       
</tr>

<tr>

    <td><h4>paq2 </h4>  </td>
    <td class="warning"><h4>2 Tutorial y 2 conferencia </h4></td>
    <td class="info"> <h4>bs. </h4></td>
    <td class="active"> <h4>bs. </h4></td>
       
</tr>

<tr>

    <td><h4>paq3 </h4>  </td>
    <td class="warning"><h4>completo </h4></td>
    <td class="info"> <h4> bs.</h4></td>
    <td class="active"> <h4>bs.</h4></td>
       
</tr>

  </table>

    </div>
</div>
