<div class="row">   
        
        <div class="costos">COSTOS</div>
        <br>
        <br>        
        <table class="table table-condensed">
    <tr>
        <td class="estudiante" > Estudiante
    <br> <br> <li class="preE">500 bs</li>
        </td>
        <td class="profecional"> Profecional
        <br> <br> <li class="preP">700 bs</li>
        </td>
    </tr>
            
        </table>
        
<br><br><br><br>
        
    </div>
</div>
