<div class="row">   
    <div class="col-xs-4">
        <h2>
        <p class="text-primary">Presentacion</p>
        </h2>
    </div>
    <div class="col-xs-8">
        
        <p>
        La carrera de Ingeniería Informática de la Universidad Autónoma Juan Misael Saracho, llevara a cabo el Congreso de Tecnologías de la Información y Comunicación, con el objeto de promover el intercambio de conocimientos en el área de las Tic’s. 
        Sera un evento de continua organización y participación de las unidades académicas del Departamento de Tarija, llegando a convertirse en un evento de trascendental importancia para el avance de las Tic´s.
        De manera Inicial la Carrera de Ingeniería Informática de la Facultad de Ciencias Integradas del Gran Chaco, tiene el grato placer de ser la sede y organizadora del “2do CONGRESO INTERNACIONAL DE TECNOLOGIAS DE LA INFORMACION Y COMUNICACION”.
        El congreso presentara una serie de actividades Académicas de Investigación e interacción Social, tratando de cubrir  las expectativas científicas y tecnológicas con temáticas del más alto nivel de conocimientos e interés en el área de la informática y sistemas que permite a los participantes desenvolverse dentro del campo académico, empresarial y de la investigación
    
        </p>
    </div>        

</div>
