<div class="row">
    <div class="col-lg-6"> </div>
    
</div>
<br>
<div class="tuto">TUTORIALES</div>
<br><br>

<table class="table table-condensed">

<!-- Ponencias -->
<tr class="colorT"> <td> TEMA </td>       <td>DOCENTE</td></tr>
<tr class="colorp"> <td> Zend Frame Word <br> </td>                <td>Ing. Robert Farfan</td></tr>
<tr class="color2"> <td> Java </td>                <td>Casi Ing. D_O_M_A</td></tr>
<tr class="color3"> <td> Bootstrap</td>             <td>Lic. Pedro</td></tr>
<tr class="info"> <td> ...</td>             <td>...</td></tr>
</table>

<div class="confe">CONFERENCIAS</div>
<br><br>

<table class="table table-condensed">

<!-- Ponencias -->
<tr class="colorT"> <td> TEMA </td>     <td>DOCENTE</td></tr>
<tr class="colorp"> <td> Tutoriales de Sistema aplicaciones de desarrollo de web <br> de informacion y gestion industrial </td>         <td>Ing. Robert Farfan</td></tr>
<tr class="color2"> <td> Tutorial, Java Avanzado</td>            <td>Casi Ing. D_O_M_A</td></tr>
<tr class="color3"> <td> Diseño Tutorial & de Bootstrap</td>         <td>Lic. Pedro</td></tr>
<tr class="info"> <td> ...</td>            <td>...</td></tr>

</table>