<div class="row">
    <div class="col-lg-6">Bienvenidos a ponencias</div>
    
</div>

<div class="tuto">TUTORIALES</div>
<br>

<table class="table table-condensed">

<!-- Ponencias -->
<tr class="active"> <td> Materias </td>     <td> Horario </td>  <td>Docente</td></tr>
<tr class="rojo"> <td> Zend </td>           <td> </td>          <td>Ing. Robert Farfan</td></tr>
<tr class="success"> <td> Java </td>        <td> </td>          <td>Lic. Pedro</td></tr>
<tr class="warning"> <td> Bootstrap</td>    <td> </td>          <td>Casi Ing. D_O_M_A</td></tr>
<tr class="info"> <td>  </td> </tr>

</table>