
<h3>
    <p class="text-primary">
    TUTORIALES        
    </p> <hr></h3>
<div class="row container">
      <div class="panel-group" id="accordion">
          
          <!--primera fila de accordion-->
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                  Moodle en 10 minutos
                </a>
              </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse">
              <div class="panel-body">
                  <div class="row">
                     <div class="col-xs-9">
                  contenido: Introduccion a moodle,<br> 
                  Instalacion de moodle,<br>
                  Elaboracion de una plataforma educativa
                    </div>
                      
                      
               <div class="col-xs-3">

                  <a href="#" class="thumbnail">
                  <img data-src="holder.js/200x150/#86D3FF:#0F3CFF" alt="...">
                  </a>

            <!--        <img src="<?php echo $this->basePath('img/F_Choque.jpg') ?>" alt="..." class="img-rounded">
            <!--        <p>
                       <a class="btn btn-success" href="<?php echo $this->url('home') ?>" target="_blank" >
                               Guillermo Choque Aspiazu
                   </a></p>-->
                    <br>

               <button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">
              Nombre del expositor1
            </button>

            <!-- Modal -->
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Nombre del expositor1</h4>
                  </div>
                  <div class="modal-body">
                      <p>Doctor en ciencias de la computacion, docente de la umsa, consultor
                          y asesor de empresas en diversos paises</p>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>  
             </div> <!--col-xs-3-->
            </div>
            </div>
            </div>
            </div><!--panel default-->

          <!--segunda fila de accordion-->
 
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">
                  Zend en 10 minutos
                </a>
              </h4>
            </div>
            <div id="collapse2" class="panel-collapse collapse">
              <div class="panel-body">
              <div class="row">
                  <div class="col-xs-9">
                  contenido: Introduccion a zend,<br> 
                  Instalacion de zend,<br>
                  Elaboracion de una plataforma educativa
                  </div>
                  <div class="col-xs-3">

                  <a href="#" class="thumbnail">
                  <img data-src="holder.js/200x150/#86D3FF:#0F3CFF" alt="...">
                  </a>

            <!--        <img src="<?php echo $this->basePath('img/F_Choque.jpg') ?>" alt="..." class="img-rounded">
            <!--        <p>
                       <a class="btn btn-success" href="<?php echo $this->url('home') ?>" target="_blank" >
                               Guillermo Choque Aspiazu
                   </a></p>-->
                    <br>

               <button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal2">
               Nombre del expositor2
               </button>

            <!-- Modal -->
            <div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">expositor2</h4>
                  </div>
                  <div class="modal-body">
                      <p>Doctor en ciencias de la computacion, docente de la umsa, consultor
                          y asesor de empresas en diversos paises</p>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>  
            </div> <!--col-xs-3-->
            </div>
            </div>
            </div>
          </div><!--panel default-->

          
          <!--tercera fila de accordion-->
 
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse3">
                  bootstrap en 10 minutos
                </a>
              </h4>
            </div>
            <div id="collapse3" class="panel-collapse collapse">
              <div class="panel-body">
              <div class="row">
                  <div class="col-xs-9">
                  contenido: Introduccion a bootstrap,<br> 
                  Instalacion de bootstrap,<br>
                  Elaboracion de una plataforma educativa
                  </div>
                  <div class="col-xs-3">

                  <a href="#" class="thumbnail">
                  <img data-src="holder.js/200x150/#86D3FF:#0F3CFF" alt="...">
                  </a>

            <!--        <img src="<?php echo $this->basePath('img/F_Choque.jpg') ?>" alt="..." class="img-rounded">
            <!--        <p>
                       <a class="btn btn-success" href="<?php echo $this->url('home') ?>" target="_blank" >
                               Guillermo Choque Aspiazu
                   </a></p>-->
                    <br>

               <button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal3">
               Nombre del expositor3
               </button>

            <!-- Modal -->
            <div class="modal fade" id="myModal3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">expositor2</h4>
                  </div>
                  <div class="modal-body">
                      <p>Doctor en ciencias de la computacion, docente de la umsa, consultor
                          y asesor de empresas en diversos paises</p>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>  
            </div> <!--col-xs-3-->
            </div>
            </div>
            </div>
          </div><!--panel default-->

                    
          
    </div>
    
</div>


<!-----------------------------------------par conferencias-->


<h3>
    <p class="text-primary">
    CONFERENCIAS        
    </p> <hr></h3>
<div class="row container">
      <div class="panel-group" id="accordion">
          
          <!--primera fila de accordion-->
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse20">
                  Moodle y la educacion
                </a>
              </h4>
            </div>
            <div id="collapse20" class="panel-collapse collapse">
              <div class="panel-body">
                  <div class="row">
                     <div class="col-xs-9">
                  contenido: Introduccion a moodle,<br> 
                  Instalacion de moodle,<br>
                  Elaboracion de una plataforma educativa
                    </div>
                      
                      
               <div class="col-xs-3">

                  <a href="#" daclass="thumbnail">
                  <img data-src="holder.js/200x150/#86D3FF:#0F3CFF" alt="...">
                  </a>

            <!--        <img src="<?php echo $this->basePath('img/F_Choque.jpg') ?>" alt="..." class="img-rounded">
            <!--        <p>
                       <a class="btn btn-success" href="<?php echo $this->url('home') ?>" target="_blank" >
                               Guillermo Choque Aspiazu
                   </a></p>-->
                    <br>

               <button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal20">
              Nombre del expositor1
            </button>

            <!-- Modal -->
            <div class="modal fade" id="myModal20" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Nombre del expositor1</h4>
                  </div>
                  <div class="modal-body">
                      <p>Doctor en ciencias de la computacion, docente de la umsa, consultor
                          y asesor de empresas en diversos paises</p>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>  
             </div> <!--col-xs-3-->
            </div>
            </div>
            </div>
            </div><!--panel default-->

          <!--segunda fila de accordion-->
 
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse21">
                  Zend en 10 minutos
                </a>
              </h4>
            </div>
            <div id="collapse21" class="panel-collapse collapse">
              <div class="panel-body">
              <div class="row">
                  <div class="col-xs-9">
                  contenido: Introduccion a zend,<br> 
                  Instalacion de zend,<br>
                  Elaboracion de una plataforma educativa
                  </div>
                  <div class="col-xs-3">

                  <a href="#" class="thumbnail">
                  <img data-src="holder.js/200x150/#86D3FF:#0F3CFF" alt="...">
                  </a>

            <!--        <img src="<?php echo $this->basePath('img/F_Choque.jpg') ?>" alt="..." class="img-rounded">
            <!--        <p>
                       <a class="btn btn-success" href="<?php echo $this->url('home') ?>" target="_blank" >
                               Guillermo Choque Aspiazu
                   </a></p>-->
                    <br>

               <button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal21">
               Nombre del expositor2
               </button>

            <!-- Modal -->
            <div class="modal fade" id="myModal21" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">expositor2</h4>
                  </div>
                  <div class="modal-body">
                      <p>Doctor en ciencias de la computacion, docente de la umsa, consultor
                          y asesor de empresas en diversos paises</p>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>  
            </div> <!--col-xs-3-->
            </div>
            </div>
            </div>
          </div><!--panel default-->

          
          <!--tercera fila de accordion-->
 
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse22">
                  bootstrap en 10 minutos
                </a>
              </h4>
            </div>
            <div id="collapse22" class="panel-collapse collapse">
              <div class="panel-body">
              <div class="row">
                  <div class="col-xs-9">
                  contenido: Introduccion a bootstrap,<br> 
                  Instalacion de bootstrap,<br>
                  Elaboracion de una plataforma educativa
                  </div>
                  <div class="col-xs-3">

                  <a href="#" class="thumbnail">
                  <img data-src="holder.js/200x150/#86D3FF:#0F3CFF" alt="...">
                  </a>

            <!--        <img src="<?php echo $this->basePath('img/F_Choque.jpg') ?>" alt="..." class="img-rounded">
            <!--        <p>
                       <a class="btn btn-success" href="<?php echo $this->url('home') ?>" target="_blank" >
                               Guillermo Choque Aspiazu
                   </a></p>-->
                    <br>

               <button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal22">
               Nombre del expositor3
               </button>

            <!-- Modal -->
            <div class="modal fade" id="myModal22" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">expositor2</h4>
                  </div>
                  <div class="modal-body">
                      <p>Doctor en ciencias de la computacion, docente de la umsa, consultor
                          y asesor de empresas en diversos paises</p>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>  
            </div> <!--col-xs-3-->
            </div>
            </div>
            </div>
          </div><!--panel default-->

                    
          
    </div>
    
</div>
