<div class="container">
            <!-- espacio para el carrusel-->
            <section id="miSlide" class="carousel slide">
                <!--circulos indicadores-->
             <ol class="carousel-indicators">
                <li data-target="#miSlide" data-slide-to="0" class="active"></li>
                <li data-target="#miSlide" data-slide-to="1"></li>
                <li data-target="#miSlide" data-slide-to="2"></li>
                <li data-target="#miSlide" data-slide-to="3"></li>
             </ol>
             <!--contenido del slider-->
             <div class="carousel-inner">
                <div class="item active">
                    <img src="<?php echo $this->basePath('img/slide1.jpg') ?>" class="adaptar">
                </div>
                <div class="item">
                    <img src="<?php echo $this->basePath('img/slide2_.jpg') ?>" class="adaptar">
                </div>
                <div class="item">
                    <img src="<?php echo $this->basePath('img/slide3_.jpg') ?>" class="adaptar">
                </div>
                <div class="item">
                    <img src="<?php echo $this->basePath('img/slide4.jpg') ?>" class="adaptar">
                </div>
             </div>
             <!--controles, flechas para desplazarse-->
             <a class="left carousel-control" href="#miSlide" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
             </a>
             <a class="right carousel-control" href="#miSlide" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
             </a>
            </section>
            <br/>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('MARCELO ANTONIO CASTRO') ?></h3>
            </div>
            <div class="panel-body">
                <img src="<?php echo $this->basePath('img/Marcelo-Chimirri2.jpg') ?>" alt="..." class="img-circle" class="adaptar">
                <p><?php echo sprintf($this->translate('Ingeniero en Sistemas de Información de la Universidad Tecnológica Nacional, Facultad de Córdoba - Argentina. Doctorando en Ciencias Informáticas. Magíster en Ingeniería de Software. Especialista en Gestión Pública. Diplomado Internacional en Gobierno Electrónico y Gestión Pública. '), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('ZF2 Development Portal') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('JORGE TERAN POMIER') ?></h3>
            </div>
            <div class="panel-body">
                 <img src="<?php echo $this->basePath('img/photo.jpg') ?>" alt="..." class="img-circle">
                <p><?php echo sprintf($this->translate('Licenciado en Informática de la UMSA, La Paz - Bolivia. Magister en Ciencias de la Computación. Diplomado de Formación Integral en Educación Superior. Diploma, E-Learning and Strategic Applications in Developing Regions. Postgrado en Ingeniería de Software. Postgrado en Diseño y Modelamiento de Software.'), '<a href="https://github.com/zendframework/modules.zendframework.com">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="https://www.facebook.com/jorge.teran.p?fref=ts" target="_blank"><?php echo $this->translate('Seguir en Facebook') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Help &amp; Support') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Ping us on IRC') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
