<div class="container">
            <!-- espacio para el carrusel-->
            <section id="miSlide" class="carousel slide">
                <!--circulos indicadores-->
             <ol class="carousel-indicators">
                <li data-target="#miSlide" data-slide-to="0" class="active"></li>
                <li data-target="#miSlide" data-slide-to="1"></li>
                <li data-target="#miSlide" data-slide-to="2"></li>
                <li data-target="#miSlide" data-slide-to="3"></li>
             </ol>
             <!--contenido del slider-->
             <div class="carousel-inner">
                <div class="item active">
                    <img src="<?php echo $this->basePath('img/slide1.jpg') ?>" class="adaptar">
                </div>
                <div class="item">
                    <img src="<?php echo $this->basePath('img/slide2_.jpg') ?>" class="adaptar">
                </div>
                <div class="item">
                    <img src="<?php echo $this->basePath('img/slide3_.jpg') ?>" class="adaptar">
                </div>
                <div class="item">
                    <img src="<?php echo $this->basePath('img/slide4.jpg') ?>" class="adaptar">
                </div>
             </div>
             <!--controles, flechas para desplazarse-->
             <a class="left carousel-control" href="#miSlide" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
             </a>
             <a class="right carousel-control" href="#miSlide" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
             </a>
            </section>
            <br/>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('PONENCIAS') ?></h3>
            </div>
            <div class="panel-body centrarimg">
                <img src="<?php echo $this->basePath('img/expo.jpg') ?>" alt="..." class="img-circle" >
                <div>
                <p><?php echo sprintf($this->translate('Ingeniero en Sistemas de Información de la Universidad Tecnológica Nacional, Facultad de Córdoba - Argentina. Doctorando en Ciencias Informáticas. Magíster en Ingeniería de Software. Especialista en Gestión Pública. Diplomado Internacional en Gobierno Electrónico y Gestión Pública. '), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
                </div>
                <p><a class="btn btn-success pull-right glyphicon glyphicon-plus" href="https://localhost/congreso2/public/ponencias" target="_blank" ></a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('CALENDARIO') ?></h3>
            </div>
            <div class="panel-body centrarimg">
                <img src="<?php echo $this->basePath('img/cale.jpg') ?>" alt="..." class="img-circle" >
                <div>
                <p><?php echo sprintf($this->translate('Ingeniero en Sistemas de Información de la Universidad Tecnológica Nacional, Facultad de Córdoba - Argentina. Doctorando en Ciencias Informáticas. Magíster en Ingeniería de Software. Especialista en Gestión Pública. Diplomado Internacional en Gobierno Electrónico y Gestión Pública. '), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
                </div>
                <p><a class="btn btn-success pull-right glyphicon glyphicon-plus" href="https://localhost/congreso2/public/calendario" target="_blank" ></a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('COSTOS') ?></h3>
            </div>
            <div class="panel-body centrarimg">
                <img src="<?php echo $this->basePath('img/calculadora.jpg') ?>" alt="..." class="img-circle" >
                <div>
                <p><?php echo sprintf($this->translate('Ingeniero en Sistemas de Información de la Universidad Tecnológica Nacional, Facultad de Córdoba - Argentina. Doctorando en Ciencias Informáticas. Magíster en Ingeniería de Software. Especialista en Gestión Pública. Diplomado Internacional en Gobierno Electrónico y Gestión Pública. '), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
                </div>
                <p><a class="btn btn-success pull-right glyphicon glyphicon-plus" href="https://localhost/congreso2/public/costos" target="_blank" ></a></p>
            </div>
        </div>
    </div>
</div>
