<div class="row">
    <div class="col-lg-6">  <h1 aling="middle">Bienvenidos a ponencias</h1></div>

    

</div>
<div class="row1">
    <div class="row1"><h2 >TUTORIALES</h2></div>
            <div class="col-lg-6">
        <br><br>
        <ul>
            
            <li>zend</li>
            <li>bootstrap</li>
            <li>java</li>
            <li>Moskit</li>
        </ul>
        
    </div>
        </div>